export const revalidate = 600;

import "./globals.css";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { Londrina_Solid } from "next/font/google";
import WagmiWrapper from "./components/WagmiWrapper";
import { getRevolutionStyles } from "@momentranks/libs";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

const londrina = Londrina_Solid({
  weight: ["400", "900", "300"],
  subsets: ["latin"],
  variable: "--font-nouns",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const revolutionId = "nouns";

  return (
    <html lang="en">
      <body
        className={`bg-page font-sans text-black ${dmSans.variable} ${londrina.variable} overscroll-none dark:text-white`}
        style={getRevolutionStyles(revolutionId)}
      >
        <WagmiWrapper>{children}</WagmiWrapper>
      </body>
    </html>
  );
}
