import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Blocks } from "@momentranks/database/models/eth/Blocks";
import { Currency } from "@momentranks/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log({ Currency: Currency.ETH });
  const test = await Blocks().getLatestIngestedBlockNumber();
  console.log({ test });
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
